import '../styles/globals.css'

import "../styles/style.css";


import "../styles/arabic.css";



import "../styles/admin.css";


import "../styles/sidebar.css";

import Adminlogin from "../components/admin/login"

import React,{useEffect,useState} from "react";

import "../styles/fonts/icomoon/style.css"

import Head from 'next/head' 
import "../styles/bootstrap.min.css"
import "../styles/bootstrap-datepicker.css"
import "../styles/jquery.fancybox.min.css"
// import "../styles/owl.carousel.min.css"
// import "../styles/owl.theme.default.min.css"
import "../styles/fonts/flaticon/font/flaticon.css"
import "../styles/aos.css"
import Header from "../components/header"


import Siderbar from "../components/sidebar/Sidebar.js"

import Link from 'next/link'

import data from "./English.json";
import 'react-toastify/dist/ReactToastify.css';
import Script from 'next/script'
import Footer from "../components/footer" 

import { useRouter } from 'next/router'
function MyApp({ Component, pageProps }) {
  const router = useRouter()
  const [direction, setDirection]=useState("");
  const [adminlogin, setAdminlogin]=useState(false)
  useEffect(()=>{
    // const langin=JSON.parse(localStorage.getItem("languageselected"));
    if(!localStorage.getItem("languageselected")){
      localStorage.setItem("languageselected","english");
    }
    else if(localStorage.getItem("languageselected")==="arabic"){

      setDirection("rtl");
    }
    console.log("admin status",localStorage.getItem("adminstatus"))
    if(!localStorage.getItem("adminstatus")){
      setAdminlogin(false)
    }
    else if(localStorage.getItem("adminstatus")){
      setAdminlogin(true)
    }
   },[])
    const logout=(e)=>{
      e.preventDefault();
      localStorage.removeItem("adminstatus");
      window.location.reload();
    }
  return (
    <>
      <div className={`site-wrap ${direction==="rtl" ? "arabic-direction": ""}`} id="home-section">
        <Head>
        <title>Switch Rental Cars </title>
        <meta name="description" content="Generated by  " />
        {/* <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700;900&display=swap" rel="stylesheet"></link> */}
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"></link>
        <link rel="icon" href="/images/logorentals2.png" />
       
       </Head>   
       {
         !router.pathname.includes("/admin") &&    <>
         <Header/>
          <span  className=" whatsapp-link  ">
            <Link  href={"tel:+971507060661"}  target="_blank">
                <a className="nav-link "><span className="icon-phone"> 
                {/* <span className='numberitself'>+971507060661</span> */}
                </span></a>
            </Link>
            <Link  href={"https://wa.me/+971507060661?text=Hello%21+I+need+to+rent+a+car%21+Can+you+help+with+me+that%3F"}  target="_blank">
              <a className="nav-link2  "><span className="icon-whatsapp">
                
                {/* <span className='numberitself'>+971507060661</span> */}
                
                </span> </a>
            </Link >
        </span>
         <Component {...pageProps} />
       <Footer />
         </>
       }
       
         {
         router.pathname.includes("/admin") &&    <>
          <div className='container-fluid'>
            
           {
            adminlogin===true &&  <div className="row">
            <div className='col-2'>
           <Siderbar/>
           </div>
          <div className='col-10'>
            <div className='adminlogout'>
            <button className=' btn btn-primary ' onClick={(e)=> logout(e)}>Logout</button>
            </div>
             <Component {...pageProps} />
          </div>
            </div>
           }
           {
            adminlogin===false && <Adminlogin/>
           }
          </div>
        
         </>
       }
       

        
      </div>
    
      
     
      </>  
  
  )
}

export default MyApp
